#!/bin/bash

num1=$((RANDOM%90+9))
num2=$((RANDOM%90+9))
num3=$((RANDOM%90+9))
num4=$((RANDOM%90+9))
num5=$((RANDOM%90+9))
SUM=$(($num1+$num2+$num3+$num4+$num5))
AVG=$(($SUM/5))
echo "The 5 numbers are $num1 $num2 $num3 $num4 $num5 "
echo "Sum of no.s are $SUM"
echo "Average of no.s are $AVG"
